ltc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from ltc_main.views import views


urlpatterns = [
    path('', views.index, name='index'),
    path('ltc/', include('ltc_main.urls')),
    # The above maps any URLs starting with ltc/ to be handled by ltc_main.
    path('admin/', admin.site.urls),
]

ltc_main/urls.py
from django.urls import path
from .views import views
from .views import timetable_views
from .views import scheduler_view
from .views import delete_views

app_name = 'ltc'

urlpatterns = [
    # Pages for authentication.
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    # Pages for adding new items.
    path('add_course/', views.add_course, name='add_course'),
    path('add_assignment/<slug:slug>/',
         views.add_assignment, name='add_assignment'),

    # Pages for viewing items.
    path('course_page/<slug:slug>/', views.course_page, name='course_page'),
    path('courses', views.courses, name='courses'),
    path('assignment_page/<slug:slug>/',
         views.assignment_page, name='assignment_page'),
    path('grade_page/<slug:slug>/', views.grade_page, name='grade_page'),
#     path('degree_page/<slug:slug>/', views.degree_page, name='degree_page'),

    # Pages for deleting items.
    path('delete_course/<slug:slug>/',
         delete_views.delete_course, name='delete_course'),
    path('delete_assignment/<slug:slug>/',
         delete_views.delete_assignment, name='delete_assignment'),

    path('delete_grade/<slug:slug>/',
         delete_views.delete_grade, name='delete_grade'),
    path('delete_degree/<slug:slug>/',
         delete_views.delete_degree, name='delete_degree'),

    # Pages for editing items.
    path('edit_course/<slug:slug>/', views.edit_course, name='edit_course'),
    path('edit_assignment/<slug:slug>/',
         views.edit_assignment, name='edit_assignment'),

    path('edit_grade/<slug:slug>/', views.edit_grade, name='edit_grade'),
#     path('edit_degree/<slug:slug>/', views.edit_degree, name='edit_degree'),

    # Event create, edit and delete
    path('add_event/<slug:slug>/<str:type>',
         views.add_event, name='add_event'),
    path('event_page/<slug:slug>/', views.event_page, name='event_page'),
    path('edit_event/<slug:slug>/', views.edit_event, name='edit_event'),
    path('delete_event/<slug:slug>/', delete_views.delete_event, name='delete_event'),

    # Pages for find meeting time
    path('find_meeting_time/', scheduler_view.find_meeting_time,
         name='find_meeting_time'),
    path('find_meeting_time/<slug:category_slug>/team_schedule_page/',
         scheduler_view.team_schedule_page, name='team_schedule_page'),

    # Pages for displaying grades
    path('grade/', views.grades, name='grades'),

    # Page for displaying the TimeTable
    path('timetable/time_table/', timetable_views.timetable, name='timetable'),

    path('staff_grades/', views.staff_grades, name='staff_grades'),
    path('grade_assignment/<slug:slug>', views.grade_assignment, name='grade_assignment'),
    
    path('join_course/', views.join_course, name='join_course'),

]

templates/ltc/add_time_slot.html
{% extends 'ltc/base_simple.html' %}
{% load staticfiles %}

{% block title_block %}
	Add time slot
{% endblock %}

{% block body_block %}
    {% if added %}
    <strong>New time slot added!</strong>
    <a href="{% url 'ltc:index' %}">Back to homepage.</a><br />
    {% endif %}
    <form id="course_form" method="post" action="{% url 'ltc:add_time_slot' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ form.as_p }}
    <!-- Provide a button to click to submit the form. -->

    <input type="submit" name="submit" value="Add new time slot" />
    </form>

{% endblock %}

templates/ltc/assignment_page.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Assignment Page {% endblock %} {% block body_block %}
<div class="row justify-content-center">
    <div class="card col-10">
        <div class="card-body">
            <h5 class="card-title">{{ course }}</h5>
            <h6>{{ title }}</h6>
            <p class="card-text">{{ detail }}</p>
            Deadline: <span class="badge badge-light">{{ assignment.deadline }}</span>
            {% if user.is_staff %}
            <div class="btn-group" role="group">
                <a
                    href="{% url 'ltc:grade_assignment' assignment.slug %}"
                    type="button"
                    class="btn btn-primary"
                    >Grade</a
                >
                <a
                    href="{% url 'ltc:edit_assignment' assignment.slug %}"
                    type="button"
                    class="btn btn-primary"
                    >Edit</a
                >
                <a
                    data-toggle="modal"
                    data-target="#Modal"
                    href=""
                    type="button"
                    class="btn btn-danger"
                    >Delete</a
                >
            </div>
            <div
                class="modal fade"
                id="Modal"
                tabindex="-1"
            >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ModalLabel">
                                Delete assignment
                            </h5>
                            <button
                                type="button"
                                class="close"
                                data-dismiss="modal"
                                aria-label="Close"
                            >
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this assignment?
                        </div>
                        <div class="modal-footer">
                            <button
                                type="button"
                                class="btn btn-secondary"
                                data-dismiss="modal"
                            >
                                Close
                            </button>
                            <a
                                href="{% url 'ltc:delete_assignment' assignment.slug %}"
                                type="button"
                                class="btn btn-danger"
                                >Delete</a
                            >
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/ltc/base_simple.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            LTC++
            {% block title_block %}
                Default title.
            {% endblock %}
        </title>
    </head>

    <body>
        <div>
        {% block body_block %}
            Default body.
        {% endblock %}
        </div>
    <a href="{% url 'ltc:index' %}">Back to homepage.</a><br />
    </body>


</html>

templates/ltc/degree_page.html
{% extends 'ltc/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Degree Page
{% endblock %}

{% block body_block %}
    Degree Name: {{ degree.name }}
    <hr />

    Including Courses:
    <ul>
    <!-- Filter the course student can have with this degree -->
    {% for course in courses %}
       <li><a href="{% url 'ltc:course_page' course.slug %}">{{ course }}</a></li>
    {% empty %}
        No course.
    {% endfor %}
    </ul>
    <hr />

    <a href="{% url 'ltc:edit_degree' degree.slug %}"><button>Edit Degree</button></a>
    <a href="{% url 'ltc:delete_degree' degree.slug %}"><button>Delete Degree</button></a>
{% endblock %}

templates/ltc/event_page.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
{{ event.name }} {% endblock %} {% block body_block %}

<div class="row">
    <div class="col-12">
        <div class="card" style="width: 100%">
            <div class="card-body">
                <h5 class="card-title">{{ event.name }}</h5>
                <hr>
                <h6>Description</h6>
                <p class="card-text">{{ event.description }}</p>
                <h6>Location</h6>
                <a href="#" id="link">{{ event.location }}</a>
                
                <p class="card-text"><h6>Time</h6>{{ event.start }} - {{ event.end }}</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card" style="width: 100%">
            <div id="map" style="height: 20em; width: 100%"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 text-right">
        {% if user.is_staff %}
        <a
            href="{% url 'ltc:edit_event' event.slug %}"
            type="button"
            class="btn btn-primary"
            >Edit</a
        >
        <a
            data-toggle="modal"
            data-target="#Modal"
            type="button"
            href=""
            class="btn btn-danger"
        >
            Delete
        </a>
        <div
            class="modal fade"
            id="Modal"
            tabindex="-1"
        >
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ModalLabel">
                            Delete event
                        </h5>
                        <button
                            type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-label="Close"
                        >
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete this event?
                    </div>
                    <div class="modal-footer">
                        <button
                            type="button"
                            class="btn btn-secondary"
                            data-dismiss="modal"
                        >
                            Close
                        </button>
                        <a
                            href="{% url 'ltc:delete_event' event.slug %}"
                            type="button"
                            href=""
                            class="btn btn-danger"
                            >Delete</a
                        >
                    </div>
                </div>
            </div>
        </div>
        {%endif%}
    </div>
</div>

<i id="latlon" hidden>{{event.geoUri}}</i>
{% endblock %} {% block footer_block %}
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.13.0/build/ol.js"></script>
<script
    type="text/javascript"
    src="{% static 'javascript/location.js' %}"
></script>
{% endblock %}

templates/ltc/find_meeting_time.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Find Meeting Time {% endblock %} {% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <h3 class="panel-title">Schedule a new Meeting</h3>
                <div id="left_pane">
                    <form
                        id="course_form"
                        method="post"
                        action="{% url 'ltc:find_meeting_time' %}"
                        enctype="multipart/form-data"
                    >
                        <div class="form-group">
                            {% csrf_token %} {{ form.non_field_errors }}
                            <div class="fieldWrapper">
                                {{ form.name.errors }}
                                <label
                                    class="h6"
                                    for="{{ form.name.id_for_label }}"
                                    >Name</label
                                >
                                {{ form.name }}
                                <small
                                    id="nameHelp"
                                    class="form-text text-muted"
                                    >A recognizable name for your meeting</small
                                >
                            </div>
                        </div>
                        <div class="form-group fieldWrapper">
                            {{ form.weekNumber.errors }}
                            <label
                                class="h6"
                                for="{{ form.weekNumber.id_for_label }}"
                                >Week Number:</label
                            >
                            {{ form.weekNumber }}
                            <small id="nameHelp" class="form-text text-muted"
                                >The week of the year in which your meeting is
                                to be held</small
                            >
                        </div>
                        <input
                            class="btn btn-dark"
                            type="submit"
                            name="submit"
                            value="Create a new meeting"
                        />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Needs to be reviewed -->
    <div class="col-sm-6 flex-equal">
        <div class="card">
            <div class="card-body">
                <div class="panel panel-primary" id="result_panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">Current Meetings</h3>
                    </div>
                    <div class="overflow-auto">
                        <div class="panel-body">
                            <ul id="right_pane" class="list-group">
                                {% if meetings %} {% for m in meetings %}
                                <a
                                    class="list-group-item"
                                    href="{% url 'ltc:team_schedule_page' m.slug %}"
                                    ><strong>
                                        {{m.name}} in week
                                        #{{m.weekNumber}}</strong
                                    >
                                </a>
                                {% endfor %} {% else %}
                                <a class="list-group-item"
                                    ><strong> No meetings</strong>
                                </a>
                                {%endif%}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block footer_block %}
<script
    type="text/javascript"
    src="{% static 'javascript/height.js' %}"
></script>
{% endblock %}

templates/ltc/grade_assignment.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Grading Page {% endblock %} {% block body_block %}
<form method="post">
    {% csrf_token %} {{ formset.management_form }} {{ formset.non_form_errors}}
    <div class="table-responsive">
        <table class="table table-striped">
            {% for form in formset.forms %} {% if forloop.first %}
            <thead>
                <tr>
                    {% for field in form.visible_fields %}
                    <th scope="col">{{ field.label|capfirst }}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% endif %}
            <tr>
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #} 
                    {% if forloop.first%}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }} {% endfor %} {% endif %} {{ field.errors }}
                    {{ field }}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Save grades</button>
</form>
{% endblock %}

templates/ltc/grade_page.html
{% extends 'ltc/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Grade Page
{% endblock %}

{% block body_block %}
    <!-- Jump with the different identity -->
    Student:
    <a href="{% url 'ltc:student_page' student.slug %}">{{ student }}</a>
    <hr />

    By Staff:
    <a href="{% url 'ltc:staff_page' staff.slug %}">{{ staff }}</a>
    <hr />

    For Course:
    <a href="{% url 'ltc:course_page' course.slug %}">{{ course }}</a>
    <hr />

    Name:{{ grade.name }}
    <br />
    Result:{{ grade.result }}
    <br />

    <a href="{% url 'ltc:edit_grade' grade.slug %}"><button>Edit Grade</button></a>
    <a href="{% url 'ltc:delete_grade' grade.slug %}"><button>Delete Grade</button></a>



{% endblock %}

templates/ltc/index.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Homepage {% endblock %} {% block body_block %}
<!-- {% if user.is_authenticated %}
Username: {{ user.username }}<br />
Staff?: {{ user.is_staff }}<br />
Admin?: {{ user.is_superuser }}<br />
{% endif%} -->
<div class="row">
    <div class="col-12">
        <div class="row">
            <h3>Welcome, {{user.username}}!</h3>
        </div>
        <div class="row">
            <h5>
                {% if user.is_staff %}Staff{% else %}Student perusing
                {{person.degree.name}}{% endif %}
            </h5>
        </div>
    </div>
</div>
<hr class="my-12" />
<div class="row">
    <div class="col-4 border-right">
        <h4>Next today</h4>
        <div class="list-group">
            <!-- List the event of this day -->
            {% for e in time %}
            <a
                href="{% url 'ltc:event_page' e.link %}"
                class="list-group-item list-group-item-action"
                >{{ e.text }}<span class="badge badge-light">{{ e.time }}</span></a
            >
            {% empty %}<a class="list-group-item list-group-item-action">
                Great job! Nothing left today.</a
            >
            {% endfor %}
        </div>
    </div>
    <div class="col-4 border-right">
        <h4>Deliverables</h4>
        <div class="list-group">
            <!-- List the assignment -->
            {% for a in assignments %}
            <a
                href="{% url 'ltc:assignment_page' a.slug %}"
                class="list-group-item list-group-item-action"
                >{{ a }}<span class="badge badge-light">{{ a.deadline }}</span></a
            >
            {% empty %}<a class="list-group-item list-group-item-action">
                Great job! Nothing left to submit.</a
            >
            {% endfor %}
        </div>
    </div>
    <div class="col-4">
        <h4>Current courses</h4>
        <div class="list-group">
            <!-- List the current course -->
            {% for c in courses_taken %}
            <a
                href="{% url 'ltc:course_page' c.slug %}"
                class="list-group-item list-group-item-action"
                >{{ c }}</a
            >
            {% empty %}<a class="list-group-item list-group-item-action"
                >No current courses.</a
            >
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/ltc/join_course.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Join Courses {% endblock %} {% block body_block %}
<div class="row pb-5">
    <div class="col-12">
        <h2 class="text-muted">Available courses</h2>
        {% if user.is_staff == False %}
        <h5>
           For the degree of {{u.degree.name}}
        </h5>
        {%endif%}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="list-group">
            <!-- display all the current course -->
            {% if courses %}{% for c in courses %}
            <a
                href="{% url 'ltc:course_page' c.slug %}"
                class="list-group-item list-group-item-action flex-column align-items-start"
            >
                <div class="row">
                    <div class="col-sm-1">
                        <img
                            src="{% static c.photo %}"
                            class="rounded"
                            alt="identicon of {{c.name}}"
                        />
                    </div>
                    <div class="col-sm-11">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{c.code}}: {{c.name}}</h5>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
            {% else %}
            <div class="card" >
                <div class="card-body">
                    <h2 class="card-title">No courses</h2>
                </div>
            </div>
            {% endif%}
        </div>
    </div>
</div>
{% endblock %}

templates/ltc/login.html
{% extends 'ltc/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}

  <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <form id="user_form" method="post" action="{% url 'ltc:login' %}">
                {% csrf_token %}
                <div class="text-center">
                    {% if login == False %}
                    
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        Invalid credentials
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                    
                    {% endif %}
                <h1 class="mb-8">Login to LTC++</h1>
                <p class="text-black-50">Please enter your login and password!</p>
                </div>

                <div class="form-outline mb-3"">
                <label class="form-label">Username</label>
                <!-- Short hint for example user and password setting -->
                <input
                    type="text"
                    class="form-control form-control-lg"
                    name="username"
                    placeholder="John Dow"
                />
                </div>

                <div class="form-outline mb-3"">
                <label class="form-label" for="typePasswordX">Password</label>
                <input
                    type="password"
                    class="form-control form-control-lg"
                    name="password"
                    placeholder="Password123"
                />
                </div>
                    <div class="text-center">
                        <button class="btn btn-primary mb-3" type="submit">Login</button>
                        <p class="mb-3">
                            Don't have an account?
                            <!-- Jump to the register page -->
                            <a href="{% url 'ltc:register' %}" class="text-black-50">Register</a>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/ltc/register.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Register {% endblock %} {% block body_block %}
<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <form
            id="user_form"
            method="post"
            action="{% url 'ltc:register' %}"
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            <div class="text-center">
                <h1 class="mb-8">Register for LTC++</h1>
                <p class="text-black-50">Please enter your details!</p>
            </div>
            <!-- Display each form and choose the register type -->
            {{ form.as_p }}
            <!-- Provide a button to click to submit the form. -->

            <div class="text-center">
                <button class="btn btn-primary mb-3" type="submit">
                    Register
                </button>
                <p class="mb-3">
                    Already have an account?
                    <!-- Jump to the register page -->
                    <a href="{% url 'ltc:login' %}" class="text-black-50"
                        >Log in!</a
                    >
                </p>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/ltc/staff_grades.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %}
Assignments to grade {% endblock %} {% block body_block %}
<div class="row pb-5">
    <div class="col-sm-6">
        <h2 class="text-muted">Assignments to grade</h2>
    </div>
</div>
<div class="list-group">
    {% for a in data%}
    <a
        href="{% url 'ltc:assignment_page' a.slug %}"
        class="list-group-item list-group-item-action"
    >
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{a.course.code}}: {{a.title}}</h5>
        </div>
        <p class="mb-1">
            {{a.deadline}}
        </p>
    </a>
    {% endfor %}
</div>
{% endblock %}

templates/ltc/student_search_partial.html
    {% for student in students %}
      <option value="{{ student.username }}">
        {{ student.username }} {{ student.last_name }}
      </option>
    {% endfor %}