ltc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from ltc_main.views import views


urlpatterns = [
    path('', views.index, name='index'),
    path('ltc/', include('ltc_main.urls')),
    # The above maps any URLs starting with ltc/ to be handled by ltc_main.
    path('admin/', admin.site.urls),
]

ltc_main/urls.py
from django.urls import path
from .views import views
from .views import timetable_views
from .views import scheduler_view
from .views import delete_views

app_name = 'ltc'

urlpatterns = [
    # Pages for authentication.
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    # Pages for adding new items.
    path('add_course/', views.add_course, name='add_course'),
    path('add_assignment/<slug:slug>/',
         views.add_assignment, name='add_assignment'),

    # Pages for viewing items.
    path('course_page/<slug:slug>/', views.course_page, name='course_page'),
    path('courses', views.courses, name='courses'),
    path('assignment_page/<slug:slug>/',
         views.assignment_page, name='assignment_page'),
    path('grade_page/<slug:slug>/', views.grade_page, name='grade_page'),
#     path('degree_page/<slug:slug>/', views.degree_page, name='degree_page'),

    # Pages for deleting items.
    path('delete_course/<slug:slug>/',
         delete_views.delete_course, name='delete_course'),
    path('delete_assignment/<slug:slug>/',
         delete_views.delete_assignment, name='delete_assignment'),

    path('delete_grade/<slug:slug>/',
         delete_views.delete_grade, name='delete_grade'),
    path('delete_degree/<slug:slug>/',
         delete_views.delete_degree, name='delete_degree'),

    # Pages for editing items.
    path('edit_course/<slug:slug>/', views.edit_course, name='edit_course'),
    path('edit_assignment/<slug:slug>/',
         views.edit_assignment, name='edit_assignment'),

    path('edit_grade/<slug:slug>/', views.edit_grade, name='edit_grade'),
#     path('edit_degree/<slug:slug>/', views.edit_degree, name='edit_degree'),

    # Event create, edit and delete
    path('add_event/<slug:slug>/<str:type>',
         views.add_event, name='add_event'),
    path('event_page/<slug:slug>/', views.event_page, name='event_page'),
    path('edit_event/<slug:slug>/', views.edit_event, name='edit_event'),
    path('delete_event/<slug:slug>/', delete_views.delete_event, name='delete_event'),

    # Pages for find meeting time
    path('find_meeting_time/', scheduler_view.find_meeting_time,
         name='find_meeting_time'),
    path('find_meeting_time/<slug:category_slug>/team_schedule_page/',
         scheduler_view.team_schedule_page, name='team_schedule_page'),

    # Pages for displaying grades
    path('grade/', views.grades, name='grades'),

    # Page for displaying the TimeTable
    path('timetable/time_table/', timetable_views.timetable, name='timetable'),

    path('staff_grades/', views.staff_grades, name='staff_grades'),
    path('grade_assignment/<slug:slug>', views.grade_assignment, name='grade_assignment'),
    
    path('join_course/', views.join_course, name='join_course'),

]

templates/ltc/add_menus/add_assignment.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %} Add
Assignment {% endblock %} {% block body_block %}

<form
    id="assignment_form"
    method="post"
    action="{% url 'ltc:add_assignment' data.course.slug %}"
    enctype="multipart/form-data"
>   
    {% csrf_token %}

    <div class="form-group">
        {{ form.non_field_errors }}
        <div class="fieldWrapper form-group">
            {{ form.title.errors }}
            <label for="{{ form.title.id_for_label }}">Title:</label>
            {{ form.title }}
            <small
                id="{{ form.title.id_for_label }}Help"
                class="form-text text-muted"
                >Title of the assignment</small
            >
        </div>
        <div class="fieldWrapper form-group">
            {{ form.detail.errors }}
            <label for="{{ form.detail.id_for_label }}">Details:</label>
            {{ form.detail }}
            <small
                id="{{ form.detail.id_for_label }}Help"
                class="form-text text-muted"
                >Details of the Assignment.</small
            >
        </div>
        <div class="fieldWrapper form-group">
            {{ form.deadline.errors }}
            <label for="{{ form.deadline.id_for_label }}">Deadline:</label>
            {{ form.deadline }}
            <small
                id="{{ form.deadline.id_for_label }}Help"
                class="form-text text-muted"
                >Deadline for assignment
                </small
            >
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add new assignment</button>
</form>

{% endblock %}

templates/ltc/add_menus/add_course.html
{% extends 'ltc/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Course
{% endblock %}

{% block body_block %}
    <form id="course_form" method="post" action="{% url 'ltc:add_course' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ form.as_p }}
    <!-- Provide a button to click to submit the form. -->

    <button type="submit" class="btn btn-primary">Add new course</button>
    </form>

{% endblock %}

templates/ltc/add_menus/add_degree.html
{% extends 'ltc/base_simple.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Degree
{% endblock %}

{% block body_block %}
    {% if added %}
    <strong>New degree added!</strong>
    <a href="{% url 'ltc:index' %}">Back to homepage.</a><br />
    {% endif %}
    <form id="course_form" method="post" action="{% url 'ltc:add_degree' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ form.as_p }}
    <!-- Provide a button to click to submit the form. -->

    <input type="submit" name="submit" value="Add new degree" />
    </form>

{% endblock %}

templates/ltc/add_menus/add_event.html
{% extends 'ltc/base.html' %} {% load staticfiles %} {% block title_block %} Add
Event {% endblock %} {% block body_block %}
<form
    id="event_form"
    method="post"
    action="{% url 'ltc:add_event' data.course.slug data.type  %}"
    enctype="multipart/form-data"
>
    {% csrf_token %} {{ form.non_field_errors }}
    <div class="row">
        <div class="fieldWrapper form-group col-12">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
            <small
                id="{{ form.name.id_for_label }}Help"
                class="form-text text-muted"
                >Name of the event</small
            >
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper form-group col-12">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}"
                >Description:</label
            >
            {{ form.description }}
            <small
                id="{{ form.description.id_for_label }}Help"
                class="form-text text-muted"
                >Description of the event</small
            >
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper form-group col-12">
            {{ form.location.errors }}
            <label for="{{ form.location.id_for_label }}">Location:</label>
            {{ form.location }}
            <small
                id="{{ form.location.id_for_label }}Help"
                class="form-text text-muted"
                >Location of the event. Can be a link.</small
            >
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper form-group col-12">
            {{ form.geoUri.errors }}
            <label for="{{ form.geoUri.id_for_label }}">Geo URI:</label>
            {{ form.geoUri }}
            <small
                id="{{ form.geoUri.id_for_label }}Help"
                class="form-text text-muted"
                >Geo URI for a physical location (Defaults to main building).
                Get your Geo URI from
                <a
                    href="https://www.openstreetmap.org/#map=15/55.8719/-4.2874"
                    target="_blank"
                    >openstreetmap.org</a
                >.</small
            >
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper form-group col-3">
            {{ form.start.errors }}
            <label for="{{ form.start.id_for_label }}"
                >Start time and date:</label
            >
            {{ form.start }}
            <small
                id="{{ form.start.id_for_label }}Help"
                class="form-text text-muted"
                >Start time for the event.</small
            >
        </div>
        <div class="fieldWrapper form-group col-3">
            {{ form.end.errors }}
            <label for="{{ form.end.id_for_label }}"
                >End time and date:</label
            >
            {{ form.end }}
            <small
                id="{{ form.end.id_for_label }}Help"
                class="form-text text-muted"
                >End time for the event.</small
            >
        </div>
        <div class="fieldWrapper form-group col-3">
            {{ form.repeat.errors }}
            <label for="{{ form.repeat.id_for_label }}"
                >Repeat:</label
            >
            {{ form.repeat }}
            <small
                id="{{ form.repeat.id_for_label }}Help"
                class="form-text text-muted"
                >Repeat (not mandatory)</small
            >
        </div>
        <div class="fieldWrapper form-group col-3">
            {{ form.repeat_until.errors }}
            <label for="{{ form.repeat_until.id_for_label }}"
                >Repeat until:</label
            >
            {{ form.repeat_until }}
            <small
                id="{{ form.repeat_until.id_for_label }}Help"
                class="form-text text-muted"
                >Repeat until (not mandatory)</small
            >
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add new event</button>
    </div>
</form>

{% endblock %}

templates/ltc/add_menus/add_grade.html
{% extends 'ltc/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Grade
{% endblock %}

{% block body_block %}
    {% if added %}
    <strong>New grade added!</strong>
    <a href="{% url 'ltc:index' %}">Back to homepage.</a><br />
    {% endif %}
    <form id="course_form" method="post" action="{% url 'ltc:add_grade' %}"
    enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ form.as_p }}
    <!-- Provide a button to click to submit the form. -->

    <input type="submit" name="submit" value="Add new grade" />
    </form>

{% endblock %}